### ISSUE TITLE
Blank window in Arch

### ISSUE THREAD

**Issue by JasonLG1979** [JasonLG1979/pithos#1]
Here @ShapeShifter499 let's see if we can't figure this out.

**Comment by ShapeShifter499** [comment]
I regret not finding this post earlier but I came back to your build of Pithos after reinstalling Arch Linux using Antergos Linux (http://antergos.com/) as the base.  I took the AUR package https://aur.archlinux.org/packages/pithos-git  and edited out TingPing's github link in the PKGBUILD file for yours to build and it seems to work fine.  Below is the PKGBUILD as I edited it

```


_pkgname=pithos
pkgname=$_pkgname-git
pkgver=422
pkgrel=1
epoch=1
pkgdesc='Pandora Internet Radio player for GNOME'
arch=('any')
url="http://pithos.github.io/"
license=('GPL3')
depends=('python' 'gtk3' 'python-gobject' 'python-dbus'
         'gst-plugins-good' 'gst-plugins-bad' 'gst-plugins-base'
         'python-pylast' 'libnotify' 'python-setuptools' 'python-cairo')
optdepends=('libkeybinder3: for media keys plugin'
            'gst-plugins-ugly: MP3 playback support'
            'libappindicator3: Unity indicator applet support'
            'python-pacparser: PAC proxy support')
makedepends=('git')
provides=("$_pkgname")
conflicts=("$_pkgname-bzr" "$_pkgname")
install="$pkgname.install"
sha256sums=('961b42a5b1105ff4625b86f87b5fa5d83a59495149cfb74b59f51e910a474ff9'
            'SKIP')

source=("$pkgname.install" "git+https://github.com/pithos/pithos.git")

pkgver() {
  cd "$srcdir/$_pkgname"
  git rev-list HEAD --count
}

package() {
  cd "$srcdir/$_pkgname"
  python setup.py install --optimize=1 --prefix=/usr --root="${pkgdir}/"
}
```

**Comment by ShapeShifter499** [comment]
I'm still testing it but I have not experienced any issues so far

**Comment by ShapeShifter499** [comment]
Ok it just froze out now during buffering, had to force close

**Comment by JasonLG1979** [comment]
I've never had any blank window issues myself on either Fedora or Ubuntu. The only real deal breaker for me is that gstreamer seems to lockup from time to time with any version past what comes with Ubuntu 14.04(don't remember off the top if my head) which is kinda crappy because I'm a sucker for new software and I hate being stuck on an old release.

**Comment by ShapeShifter499** [comment]
So it's gstreamer causing the player to lock up requiring a force close every so often?

**Comment by JasonLG1979** [comment]
Are you a Pandora one subscriber? Because in my experience the lower bitrate streams which are AAC(mp4) don't lockup gstreamer. As far as I can tell it's a bug in the download buffer. It doesn't like MP3's.

**Comment by JasonLG1979** [comment]
There's really not much I can do about gstreamer. I filed a bug on Pithos about it but the devs haven't followed through by pushing the issue upstream.

**Comment by JasonLG1979** [comment]
If you downgrade gstreamer to whatever version came with Ubuntu 14.04 you should have no problem. It never locks up on Ubuntu 14.04.

**Comment by ShapeShifter499** [comment]
Shouldn't qAndora work better since it uses vlc instead?

**Comment by ShapeShifter499** [comment]
I have a issue with that btw, I posted it in JeffHoogland's qAndora github    https://github.com/JeffHoogland/qAndora/issues/17

**Comment by ShapeShifter499** [comment]
Btw yes I do subscribe to PandoraOne.  Also not sure if this helps much but I just got this from running your version of Pithos in cli.

```
[lance@Arch-chromebook bin]$ pithos 
ERROR - mediakeys:on_enable:124 - Could not bind media keys
WARNING - pithos:eb:320 - Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/pithos/gobject_worker.py", line 37, in _run
    result = command(*args)
  File "/usr/lib/python3.4/site-packages/pithos/pandora/pandora.py", line 288, in get_playlist
    playlist = self.pandora.json_call('station.getPlaylist', {'stationToken': self.idToken}, https=True)
  File "/usr/lib/python3.4/site-packages/pithos/pandora/pandora.py", line 121, in json_call
    response = self.opener.open(req, timeout=HTTP_TIMEOUT)
  File "/usr/lib/python3.4/urllib/request.py", line 455, in open
    response = self._open(req, data)
  File "/usr/lib/python3.4/urllib/request.py", line 473, in _open
    '_open', req)
  File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 1217, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.4/urllib/request.py", line 1177, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.4/http/client.py", line 1172, in getresponse
    response.begin()
  File "/usr/lib/python3.4/http/client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.4/socket.py", line 371, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.4/ssl.py", line 618, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/pithos/plugins/scrobble.py", line 56, in song_ended
    self.scrobble(song)
  File "/usr/lib/python3.4/site-packages/pithos/plugins/scrobble.py", line 78, in scrobble
    if song.duration > 30 and (song.position > 240 or song.position > song.duration/2):
TypeError: unorderable types: NoneType() > int()
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/pithos/plugins/scrobble.py", line 56, in song_ended
    self.scrobble(song)
  File "/usr/lib/python3.4/site-packages/pithos/plugins/scrobble.py", line 78, in scrobble
    if song.duration > 30 and (song.position > 240 or song.position > song.duration/2):
TypeError: unorderable types: NoneType() > int()
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/pithos/plugins/scrobble.py", line 56, in song_ended
    self.scrobble(song)
  File "/usr/lib/python3.4/site-packages/pithos/plugins/scrobble.py", line 78, in scrobble
    if song.duration > 30 and (song.position > 240 or song.position > song.duration/2):
TypeError: unorderable types: NoneType() > int()
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/pithos/plugins/scrobble.py", line 56, in song_ended
    self.scrobble(song)
  File "/usr/lib/python3.4/site-packages/pithos/plugins/scrobble.py", line 78, in scrobble
    if song.duration > 30 and (song.position > 240 or song.position > song.duration/2):
TypeError: unorderable types: NoneType() > int()
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/pithos/plugins/scrobble.py", line 56, in song_ended
    self.scrobble(song)
  File "/usr/lib/python3.4/site-packages/pithos/plugins/scrobble.py", line 78, in scrobble
    if song.duration > 30 and (song.position > 240 or song.position > song.duration/2):
TypeError: unorderable types: NoneType() > int()
[lance@Arch-chromebook bin]$ 
```

**Comment by JasonLG1979** [comment]
Yep I accidently sent a merge request for some screwed up code. I'll fix it tomorrow...

But even then qAndora isn't perfect either. It's a little rough around the edges. See my issue regarding the vlc audio back end. I wouldn't call it a Pithos replacement by any means.

**Comment by ShapeShifter499** [comment]
Hmm. So the workaround for pithos (wether I'm running your version or TingPing's) is to downgrade gstreamer OR keep killing and reloading pithos when it locks up

**Comment by JasonLG1979** [comment]
Did you install pylast? I've never seen those error messages but a lot of them talk about the scribble plugin. Not sure what would happen if you tried to unable the plugin without pylast?

**Comment by JasonLG1979** [comment]
*scroble*

**Comment by ShapeShifter499** [comment]
I have pylast installed from the aur https://aur.archlinux.org/packages/python-pylast/

**Comment by JasonLG1979** [comment]
That page lists it as depending on python. I'm not sure about arch but in Ubuntu python means python 2. Make sure that's the python3 version of pylast.

**Comment by ShapeShifter499** [comment]
Python in Arch usually means Python3, the Python package it's linked to being depended on is version 3.4.2-2

**Comment by JasonLG1979** [comment]
OK then I'm not sure what to tell you. I haven't changed any of the code that the trace mentioned.

**Comment by JasonLG1979** [comment]
Are you behind a proxy?

**Comment by ShapeShifter499** [comment]
I'm not,  I'm connected in the US via Comcrap (er Comcast)

**Comment by JasonLG1979** [comment]
Reading it closer it looks like Pithos is having trouble connecting.

**Comment by ShapeShifter499** [comment]
I restarted pithos and it seems fine again until the next lock up

**Comment by JasonLG1979** [comment]
Does Pithos show up at all when you try it? And have you checked to make sure Pandora is up?

**Comment by ShapeShifter499** [comment]
I'm listening right now to pithos/pandora. Seems it was a one time error

**Comment by ShapeShifter499** [comment]
Would you be able to tell me which version of gstreamer is in 14.04? I might try downgrading it

**Comment by JasonLG1979** [comment]
I want to say 1.2

**Comment by JasonLG1979** [comment]
@ShapeShifter499 I'm in the process of replacing the Gstreamer audio back end with VLC. I'm in the very early stages but it looks promising. If successful it should hopefully end the whole locking up problem.(cross your fingers,lol!!!)

**Comment by ShapeShifter499** [comment]
Sounds awesome! Let me know when this happens, I'll test that version right away.

**Comment by JasonLG1979** [comment]
It works mostly. You don't get all the fancy debugging that gstreamer has but it plays music. When I'm done tweaking it a little I'll post the code for you to checkout. I don't see it as a replacement for gstreamer, just something to get us by until gstreamer is fixed.

**Comment by JasonLG1979** [comment]
Well it's up. It works for the most part. Though here are a couple known issues.

Of course you'll need to have VLC installed as it depends on libVLC for audio playback.

The scaling in the volume slider in Pithos is incorrect(working on that)

Either I'm not implementing them correctly(which is VERY possible) or the VLC python bindings have a small memory leak. I listened for 5 hours the other day and it went from about 28MB to 45MB according to  the KDE system monitor.

The VLC bindings don't keep very good time. The track time clock make slip from every now and then. Doesn't effect playback purely cosmetic.

Ad detection is removed/disabled for now.

**Comment by JasonLG1979** [comment]
Testing it out on Fedora 21 and everything works pretty good except the small memory leak(if it even is a memory leak). I'm not sure if maybe I need to explicitly clear the buffer/cache at song changes, if the leak is an artifact of python's memory management, or it isn't a leak and VLC is in fact just reusing the same space in memory for it's buffer/cache but never shrinking it. I say that because memory usage seems to level off after a couple songs.

**Comment by JasonLG1979** [comment]
@ShapeShifter499, A fix for the lockup bug is in the works. I'm currently testing it on Ubuntu 14.10, so far so good. see https://github.com/pithos/pithos/issues/143. You could probably build it from source on Arch.(https://launchpad.net/~glennimoss/+archive/ubuntu/ppa/+files/gst-plugins-base1.0_1.4.3-1ubuntu1ppa27%7Eubuntu14.10.1.tar.xz) If all goes well I'll be deleting this fork after a while and pushing the useful changes back to Pithos the proper way. After all the main reason for this fork was trying to solve the lockup problem.

**Comment by ShapeShifter499** [comment]
Sorry to reopen this but I wanted to ask did you revert to using Gstreamer with a patch to try to fix the lockup?  I did not get a chance to try the VLC supported version of pithos you created. If I understand what I'm reading, I can test the patched pithos from the ppa or try the VLC pithos from your forked pithos git

**Comment by JasonLG1979** [comment]
https://www.dropbox.com/s/bcw3ndr1x1th3gs/pithosVLC.tar.gz?dl=0

**Comment by JasonLG1979** [comment]
Yep. The only reason for using VLC as a backend was because Gstreamer was jacked up. Now that there's a patch to fix the deadlock there's no real point in continuing that line of development. But here's the latest VLC backend version.

https://www.dropbox.com/s/bcw3ndr1x1th3gs/pithosVLC.tar.gz?dl=0
